### ISSUE TITLE
document how to run tests

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-javascript#1]
Hi! I just created an issue at https://github.com/IQSS/dataverse-jenkins/issues/17 to test this repo using https://jenkins.dataverse.org but I'm enough of a Javascript newbie that I'm not 100% sure how to run the tests. Could the steps please be added to README.md or CONTRIBUTING.md? Thanks!

**Comment by tainguyenbui** [comment]
Hi @pdurbin, I just updated README.md to document how to run tests, lint and format checks. Thanks for creating the issue

**Comment by pdurbin** [comment]
@tainguyenbui pull request #2 looks great and I just approved it. I'm a little confused about if you're talking about CI built into npm? I don't see a .travis or .circleci file.

**Comment by tainguyenbui** [comment]
@pdurbin, I've not integrated this repository with any CI yet, I thought we would go for IQSS Jenkins pipeline.

Whichever we decide to go for, we would only need a machine with nodejs installed, ideally `yarn` too and then we would run the following workflow:

Format check > Lint Check > Build > Unit tests

**Comment by pdurbin** [comment]
@tainguyenbui that sounds perfect. Thanks! I'm not sure when I'll get to https://github.com/IQSS/dataverse-jenkins/issues/17 but it's on my list! 😄
