### ISSUE TITLE
Timing issue in FilesRepository.test.ts

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-client-javascript#101]
Because of a timing issue, sometimes the integration test for FilesRepository fails, due to an OptimisticLockException.  This is happening in my local environment, but not in the Github action.  I tried it in the develop branch, and also https://github.com/IQSS/dataverse-client-javascript/tree/95-get-dataset-locks. 

Edit (11/01) - Guillermo:

The error also occurs in the GitHub action:
https://github.com/IQSS/dataverse-client-javascript/actions/runs/6719463036/job/18261139350 

From PR: https://github.com/IQSS/dataverse-client-javascript/pull/99

Edit (11/02) - Guillermo:

I have a failure also on my localhost.

To reproduce, build the library then run:
` npm run test:integration`

 Attached is the error output:
[error.txt](https://github.com/IQSS/dataverse-client-javascript/files/13217908/error.txt)

**Comment by GPortas** [comment]
I've decided to temporarily skip this test in the code until we fix it to avoid breaking the package build and GPR push in the GitHub action @ekraffmiller.
