### ISSUE TITLE
Create use case to get the file citation

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-client-javascript#117]
**Overview of the Feature Request**

The aim is to develop a new use case for retrieving a specific file citation 

This use case will be consumed from Dataverse SPA, although it should be applicable to other scenarios.

This use case depends on this issue to implement the API endpoint:
- https://github.com/IQSS/dataverse/issues/10240

**What kind of user is the feature intended for?**

- Use case consumer

**What inspired the request?**

- https://github.com/IQSS/dataverse-frontend/pull/269#issuecomment-1874193736
- https://github.com/IQSS/dataverse-frontend/issues/249

**What existing behavior do you want changed?**

None

**Any brand new behavior do you want to add to Dataverse?**

Get File citation use case

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse-frontend/issues/249

**Comment by GPortas** [comment]
Waiting: https://github.com/IQSS/dataverse/pull/10246
