### ISSUE TITLE
add isReleased to the getCollection useCase

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-client-javascript#139]
For the SPA, we need to display an 'Unpublished' label on the Collections page, if the collection hasn't been released.  To do this we need to add an isReleased field to the payload of the getCollection useCase.

This issue depends on adding the field to the API: https://github.com/IQSS/dataverse/issues/10448

**Comment by GPortas** [comment]
The required API extension is already in QA, removing the waiting label.
