### ISSUE TITLE
Create use cases for API Token management 

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-client-javascript#190]
## Overview of the Feature Request

Create use cases for API Token management:

- Get api token
- Create api token
- Recreate api token
- Revoke api token

These use cases will be consumed by the SPA.

## What Inspired the Request?

- https://github.com/IQSS/dataverse-frontend/pull/479 

## What Existing Behavior Do You Want Changed?

- None

## Any Brand New Behavior Do You Want to Add to js-dataverse?

- Create use cases for API Token management

**Comment by g-saracca** [comment]
Hi @GPortas , I think we will need an extra small use case from this Native API endpoint [Find a Token’s Expiration Date](https://guides.dataverse.org/en/latest/api/native-api.html#id162) to display a message to the user that the token has expired.

![Image](https://github.com/user-attachments/assets/df148aaa-0e27-4d59-aedd-94fefaa2f680)
