### ISSUE TITLE
Add facet results to getCollectionItems use case 

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-client-javascript#228]
For the SPA Q4 feature "Collection Page: all filtering options", we need to get the facet results for the Collection Page. 
<img width="650" alt="Screenshot 2024-12-04 at 7 11 16 PM" src="https://github.com/user-attachments/assets/eb82e34f-9487-4450-b38d-cce6e31d45a8">

To get this data, we can use the use `show_facets=true` param in the Dataverse Search API.  
The getCollectionItems use case should be updated to return this data, possibly by adding a boolean field `showFacets` to the CollectionSearchCriteria object.

**Comment by g-saracca** [comment]
Closing as it will be addressed in https://github.com/IQSS/dataverse-client-javascript/issues/229
