### ISSUE TITLE
automatically reformat code

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-javascript#58]
As a test I just messed with some code and gave it some awful formatting:

```
import { ApiRepository } from '../../../core/infra/repositories/ApiRepository'; import { IAuthRepository } from '../../domain/repositories/IAuthRepository';

export class AuthRepository extends ApiRepository implements IAuthRepository {
 public async logout(): Promise<void> {
     return this.doPost('/logout', '')
         .then(() => undefined)
            .catch((error) => {
               throw error;
                    });
                      }
                           }
```

I was able to push it to a branch (which I plan to delete but for now you can see the commit at fbebab5).

I would love to have the feature from the frontend where code is formatted automatically. It was added somewhere around here: https://github.com/IQSS/dataverse-frontend/commit/f9af164688df59c390cd078a39436ce155017b3f

There's some discussion here as well: https://github.com/IQSS/dataverse-frontend/pull/4#discussion_r1108682935

That is to say, it would be great to reformat the code automatically before it is pushed to a branch. This will keep our code formatted the same way no matter how the code is edited.

**Comment by MellyGray** [comment]
@cmbz I moved this issue from "SPRINT READY" to "This Sprint" because the remaining frontend issues in "This Sprint" were in "Waiting". Therefore, I chose this issue to work on while those issues resolve their dependencies. I hope that's ok, thanks!
