### ISSUE TITLE
ClojureScript support

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-javascript#8]
Just a heads up that I kicked off a conversation about enabling support for ClojureScript at https://github.com/cljsjs/packages/issues/1972 and now there's a pull request at https://github.com/cljsjs/packages/pull/1974 :tada: 

I don't think there is anything to do at this time (unless anyone reading this is a ClojureScript developer and wants to try out that pull request) but in the future it might be nice to update the README to mention that ClojureScript support is enabled through this npm package (assuming that pull request is merged).

**Comment by tainguyenbui** [comment]
Great stuff @pdurbin 🚀 , keep me posted on that PR

**Comment by pdurbin** [comment]
@tainguyenbui will do! It looks like https://github.com/cljsjs/packages/pull/1973 (axios) needs to be merged first but I don't really know what I'm talking about. 😄

**Comment by pdurbin** [comment]
@tainguyenbui hi! Both of these pull requests by @2knu (thank you!!) have been merged:

- axios: https://github.com/cljsjs/packages/pull/1973
- js-dataverse: https://github.com/cljsjs/packages/pull/1974

Because of this, a "cljsjs/js-dataverse package" appears at http://cljsjs.github.io like this:

![Screen Shot 2020-01-07 at 10 00 03 AM](https://user-images.githubusercontent.com/21006/71905819-e8166c00-3136-11ea-9b85-af32b16515b6.png)

I just created https://github.com/IQSS/dataverse/issues/6487 to list ClojureScript as one of the client libraries in the Dataverse API Guide (and hopefully test it a bit first).

I notice that the version in CLJSJS is 0.1.17 but you've already released v1.0.27.

@2knu gave some helpful instruction at https://github.com/cljsjs/packages/issues/1972#issuecomment-533724617 about how to keep the package in CLJSJS up to date with the version on npm. I'm not asking you to do this. I'm just trying to keep all this great stuff straight in my head. 😄 

Do you think I should go ahead and close this issue? Are we done, thanks to @2knu?

**Comment by tainguyenbui** [comment]
hi @pdurbin and @2knu! thank you for getting this to ClojureScript 🚀 
I was wondering the other day how I could keep it up to date so that information you just shared could be handy one day.

I think we could go ahead and close it.

Again, thank you very much

**Comment by pdurbin** [comment]
Cool. Closing, thanks again, all! People can follow these two (currently open) issues for more:

- Add js-dataverse: https://github.com/cljsjs/packages/issues/1972
- Add ClojureScript to list of Dataverse client libraries (SDKs): https://github.com/IQSS/dataverse/issues/6487
