### ISSUE TITLE
Add use case to get the total space consumed by the files of a particular dataset version

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-client-javascript#86]
**Overview of the Feature Request**

We need a use case to get the total space consumed by the files of a particular dataset version.

This use case will allow the SPA to know the total space consumed by the files when the user selects "select all" in the files tab, without needing to retrieve all the files (without pagination, could be an expensive operation) and apply client side logic to calculate the size.

The use case may be useful for other scenarios where the total file size may be useful, for example, metrics-related applications.

We need to explore the Dataverse API to determine if an endpoint exists to support the new use case or if it needs to be created (Create API spike issue in such case).

**What kind of user is the feature intended for?**

Package consumer

**What inspired the request?**

- Discussion on https://github.com/IQSS/dataverse-frontend/pull/156

**What existing behavior do you want changed?**

None

**Any brand new behavior do you want to add to Dataverse?**

New use case for getting the total space consumed by the files of a particular dataset version

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse-frontend/pull/156

**Comment by MellyGray** [comment]
Added the waiting tag because the API needs to be extended to finishing this issue

- https://github.com/IQSS/dataverse/issues/9945
